
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCoop.Data
{

using System;
    using System.Collections.Generic;
    
public partial class AttributeBusinessProcess
{

    public int BusinessProcessId { get; set; }

    public int AttributeId { get; set; }

    public Nullable<System.DateTime> CreationTime { get; set; }



    public virtual BusinessProcessAttribute BusinessProcessAttribute { get; set; }

    public virtual BusinessProcess BusinessProcess { get; set; }

}

}
