
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCoop.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Incident
{

    public Incident()
    {

        this.IncidentOrgUnits = new HashSet<IncidentOrgUnit>();

        this.IncidentUsers = new HashSet<IncidentUser>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public double Lat { get; set; }

    public double Lng { get; set; }

    public string Address { get; set; }

    public int Type { get; set; }

    public int Priority { get; set; }

    public int FacilityType { get; set; }

    public System.DateTime StartTime { get; set; }

    public long Duration { get; set; }

    public string Description { get; set; }



    public virtual ICollection<IncidentOrgUnit> IncidentOrgUnits { get; set; }

    public virtual ICollection<IncidentUser> IncidentUsers { get; set; }

}

}
