
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCoop.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Component
{

    public Component()
    {

        this.DocumentTemplates = new HashSet<DocumentTemplate>();

    }


    public int Id { get; set; }

    public string Name { get; set; }



    public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }

}

}
