
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCoop.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Group
{

    public Group()
    {

        this.OrgUnitGroupPermissions = new HashSet<OrgUnitGroupPermission>();

        this.UserGroups = new HashSet<UserGroup>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public System.DateTime ModifiedDate { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int ModifiedByUserId { get; set; }

    public int CreatedByUserId { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual ICollection<OrgUnitGroupPermission> OrgUnitGroupPermissions { get; set; }

    public virtual ICollection<UserGroup> UserGroups { get; set; }

}

}
