//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int UserId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
