
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCoop.Data
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.Groups = new HashSet<Group>();

        this.Groups1 = new HashSet<Group>();

        this.IncidentUsers = new HashSet<IncidentUser>();

        this.OrgUnits = new HashSet<OrgUnit>();

        this.OrgUnitUserPermissions = new HashSet<OrgUnitUserPermission>();

        this.SysEvents = new HashSet<SysEvent>();

        this.UserGroups = new HashSet<UserGroup>();

        this.WorkspaceTemplates = new HashSet<WorkspaceTemplate>();

        this.WorkspaceTemplates1 = new HashSet<WorkspaceTemplate>();

    }


    public int Id { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Password { get; set; }

    public int TypeId { get; set; }

    public int PermissionLevelId { get; set; }

    public System.DateTime LastAcitve { get; set; }



    public virtual ICollection<Group> Groups { get; set; }

    public virtual ICollection<Group> Groups1 { get; set; }

    public virtual ICollection<IncidentUser> IncidentUsers { get; set; }

    public virtual ICollection<OrgUnit> OrgUnits { get; set; }

    public virtual ICollection<OrgUnitUserPermission> OrgUnitUserPermissions { get; set; }

    public virtual PermissionLevel PermissionLevel { get; set; }

    public virtual ICollection<SysEvent> SysEvents { get; set; }

    public virtual ICollection<UserGroup> UserGroups { get; set; }

    public virtual ICollection<WorkspaceTemplate> WorkspaceTemplates { get; set; }

    public virtual ICollection<WorkspaceTemplate> WorkspaceTemplates1 { get; set; }

}

}
