
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCoop.Data
{

using System;
    using System.Collections.Generic;
    
public partial class WorkspaceTemplateComponent
{

    public int WorkspaceTemplateId { get; set; }

    public int ComponentId { get; set; }

    public System.DateTime CreationTime { get; set; }



    public virtual Component Component { get; set; }

    public virtual WorkspaceTemplate WorkspaceTemplate { get; set; }

}

}
