
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyCoop.Data
{

using System;
    using System.Collections.Generic;
    
public partial class WorkspaceTemplate
{

    public WorkspaceTemplate()
    {

        this.OrgUnits = new HashSet<OrgUnit>();

        this.DocumentTemplates = new HashSet<DocumentTemplate>();

        this.Components = new HashSet<Component>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public System.DateTime CreationTime { get; set; }

    public System.DateTime ModificationTime { get; set; }

    public int CreatedByUserId { get; set; }

    public int ModifiedByUserId { get; set; }



    public virtual ICollection<OrgUnit> OrgUnits { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }

    public virtual ICollection<Component> Components { get; set; }

}

}
